# Generated by Django 5.0 on 2024-01-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_userdashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
